// <auto-generated />
using System;
using EcoTrack.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoTrack.API.Migrations
{
    [DbContext(typeof(EcoTrackDbContext))]
    partial class EcoTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoTrack.API.Models.Activity", b =>
                {
                    b.Property<int>("AktiviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("aktivite_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AktiviteId"));

                    b.Property<DateTime>("AktiviteTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aktivite_tarihi");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer")
                        .HasColumnName("kategori_id");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer")
                        .HasColumnName("kullanici_id");

                    b.Property<double>("TuketimDegeri")
                        .HasColumnType("double precision")
                        .HasColumnName("tuketim_degeri");

                    b.HasKey("AktiviteId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("aktiviteler", (string)null);
                });

            modelBuilder.Entity("EcoTrack.API.Models.ActivityCategory", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("kategori_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KategoriId"));

                    b.Property<string>("BirimTipi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("birim_tipi");

                    b.Property<double>("EmisyonKatsayisi")
                        .HasColumnType("double precision")
                        .HasColumnName("emisyon_katsayisi");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kategori_adi");

                    b.HasKey("KategoriId");

                    b.ToTable("aktivite_kategorileri", (string)null);

                    b.HasData(
                        new
                        {
                            KategoriId = 1,
                            BirimTipi = "km",
                            EmisyonKatsayisi = 0.14499999999999999,
                            KategoriAdi = "Ulaşım - Araba"
                        },
                        new
                        {
                            KategoriId = 2,
                            BirimTipi = "km",
                            EmisyonKatsayisi = 0.02,
                            KategoriAdi = "Ulaşım - Metro"
                        },
                        new
                        {
                            KategoriId = 3,
                            BirimTipi = "km",
                            EmisyonKatsayisi = 0.088999999999999996,
                            KategoriAdi = "Ulaşım - Otobüs"
                        },
                        new
                        {
                            KategoriId = 4,
                            BirimTipi = "km",
                            EmisyonKatsayisi = 0.10299999999999999,
                            KategoriAdi = "Ulaşım - Motosiklet"
                        },
                        new
                        {
                            KategoriId = 5,
                            BirimTipi = "km",
                            EmisyonKatsayisi = 0.0,
                            KategoriAdi = "Ulaşım - Bisiklet"
                        },
                        new
                        {
                            KategoriId = 6,
                            BirimTipi = "km",
                            EmisyonKatsayisi = 0.255,
                            KategoriAdi = "Ulaşım - Uçak"
                        },
                        new
                        {
                            KategoriId = 7,
                            BirimTipi = "kWh",
                            EmisyonKatsayisi = 0.48099999999999998,
                            KategoriAdi = "Enerji - Elektrik"
                        },
                        new
                        {
                            KategoriId = 8,
                            BirimTipi = "m3",
                            EmisyonKatsayisi = 2.04,
                            KategoriAdi = "Enerji - Doğalgaz"
                        },
                        new
                        {
                            KategoriId = 9,
                            BirimTipi = "kg",
                            EmisyonKatsayisi = 2.8599999999999999,
                            KategoriAdi = "Enerji - Kömür"
                        },
                        new
                        {
                            KategoriId = 10,
                            BirimTipi = "porsiyon",
                            EmisyonKatsayisi = 6.6100000000000003,
                            KategoriAdi = "Beslenme - Kırmızı Et"
                        },
                        new
                        {
                            KategoriId = 11,
                            BirimTipi = "porsiyon",
                            EmisyonKatsayisi = 3.1899999999999999,
                            KategoriAdi = "Beslenme - Beyaz Et"
                        },
                        new
                        {
                            KategoriId = 12,
                            BirimTipi = "porsiyon",
                            EmisyonKatsayisi = 1.5,
                            KategoriAdi = "Beslenme - Vejetaryen"
                        },
                        new
                        {
                            KategoriId = 13,
                            BirimTipi = "porsiyon",
                            EmisyonKatsayisi = 0.90000000000000002,
                            KategoriAdi = "Beslenme - Vegan"
                        },
                        new
                        {
                            KategoriId = 14,
                            BirimTipi = "adet",
                            EmisyonKatsayisi = 0.083000000000000004,
                            KategoriAdi = "Atık - Plastik Şişe"
                        },
                        new
                        {
                            KategoriId = 15,
                            BirimTipi = "kg",
                            EmisyonKatsayisi = 0.021000000000000001,
                            KategoriAdi = "Atık - Kağıt/Karton"
                        },
                        new
                        {
                            KategoriId = 16,
                            BirimTipi = "adet",
                            EmisyonKatsayisi = 0.010999999999999999,
                            KategoriAdi = "Atık - Cam"
                        },
                        new
                        {
                            KategoriId = 17,
                            BirimTipi = "kg",
                            EmisyonKatsayisi = 0.39000000000000001,
                            KategoriAdi = "Atık - Organik"
                        });
                });

            modelBuilder.Entity("EcoTrack.API.Models.CarbonCalculation", b =>
                {
                    b.Property<int>("HesaplamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("hesaplama_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HesaplamaId"));

                    b.Property<int>("AktiviteId")
                        .HasColumnType("integer")
                        .HasColumnName("aktivite_id");

                    b.Property<DateTime>("HesaplamaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hesaplama_tarihi");

                    b.Property<double>("KarbonMiktari")
                        .HasColumnType("double precision")
                        .HasColumnName("karbon_miktari");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer")
                        .HasColumnName("kullanici_id");

                    b.HasKey("HesaplamaId");

                    b.HasIndex("AktiviteId")
                        .IsUnique();

                    b.HasIndex("KullaniciId");

                    b.ToTable("karbon_hesaplamalari", (string)null);
                });

            modelBuilder.Entity("EcoTrack.API.Models.Recommendation", b =>
                {
                    b.Property<int>("OneriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("oneri_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OneriId"));

                    b.Property<double>("EtkiSkoru")
                        .HasColumnType("double precision")
                        .HasColumnName("etki_skoru");

                    b.Property<int?>("HesaplamaId")
                        .HasColumnType("integer")
                        .HasColumnName("hesaplama_id");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer")
                        .HasColumnName("kullanici_id");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturulma_tarihi")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("OneriMetni")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("oneri_metni");

                    b.Property<bool>("UygulandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("uygulandi_mi");

                    b.HasKey("OneriId");

                    b.HasIndex("HesaplamaId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("oneriler", (string)null);
                });

            modelBuilder.Entity("EcoTrack.API.Models.User", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("kullanici_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ad_soyad");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("eposta");

                    b.Property<double>("HedeflenenKarbonLimiti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(56.0)
                        .HasColumnName("hedeflenen_karbon_limiti");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kayit_tarihi")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("SifrelenmisSifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sifrelenmis_sifre");

                    b.HasKey("KullaniciId");

                    b.HasIndex("Eposta")
                        .IsUnique()
                        .HasDatabaseName("IX_kullanicilar_eposta");

                    b.ToTable("kullanicilar", (string)null);
                });

            modelBuilder.Entity("EcoTrack.API.Models.UserStatistic", b =>
                {
                    b.Property<int>("IstatistikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("istatistik_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IstatistikId"));

                    b.Property<DateTime>("GuncellenmeZamani")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncellenme_tarihi")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<int>("GunlukSeri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("gunluk_seri");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer")
                        .HasColumnName("kullanici_id");

                    b.Property<string>("RozetAdi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("İlk Adım")
                        .HasColumnName("rozet_adi");

                    b.Property<double>("ToplamTasarruf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("toplam_tasarruf");

                    b.HasKey("IstatistikId");

                    b.HasIndex("KullaniciId")
                        .IsUnique()
                        .HasDatabaseName("IX_kullanici_istatistikleri_kullanici_id");

                    b.ToTable("kullanici_istatistikleri", (string)null);
                });

            modelBuilder.Entity("EcoTrack.API.Models.Activity", b =>
                {
                    b.HasOne("EcoTrack.API.Models.ActivityCategory", "Category")
                        .WithMany("Activities")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoTrack.API.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTrack.API.Models.CarbonCalculation", b =>
                {
                    b.HasOne("EcoTrack.API.Models.Activity", "Activity")
                        .WithOne("CarbonCalculation")
                        .HasForeignKey("EcoTrack.API.Models.CarbonCalculation", "AktiviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoTrack.API.Models.User", "User")
                        .WithMany("CarbonCalculations")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTrack.API.Models.Recommendation", b =>
                {
                    b.HasOne("EcoTrack.API.Models.CarbonCalculation", "CarbonCalculation")
                        .WithMany("Recommendations")
                        .HasForeignKey("HesaplamaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoTrack.API.Models.User", "User")
                        .WithMany("Recommendations")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarbonCalculation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTrack.API.Models.UserStatistic", b =>
                {
                    b.HasOne("EcoTrack.API.Models.User", "User")
                        .WithOne("UserStatistic")
                        .HasForeignKey("EcoTrack.API.Models.UserStatistic", "KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTrack.API.Models.Activity", b =>
                {
                    b.Navigation("CarbonCalculation");
                });

            modelBuilder.Entity("EcoTrack.API.Models.ActivityCategory", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("EcoTrack.API.Models.CarbonCalculation", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("EcoTrack.API.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("CarbonCalculations");

                    b.Navigation("Recommendations");

                    b.Navigation("UserStatistic");
                });
#pragma warning restore 612, 618
        }
    }
}
